### ISSUE TITLE
Proof Verification Failing

### ISSUE THREAD

**Issue by TalDerei** [a16z/zkdrops#7]
So upon running "npx hardhat compile" and "npx hardhat test", all of the tests pass normally (with existing keys and verification contract already generated in the repo).

But when regenerating the keys and verification contract by running "./build_scripts/build_all.sh", and then running "npx hardhat compile" and "npx hardhat test", the proof verification fails. This wasn't an issue a few months ago, but I suspect there's been an update to snarkjs/circom, or the solidity verifier contract that modifies the solidity call data. Nothing in your core repos / library has changed otherwise.

In any regard, if you try rerunning the test-cases in this repo, you'll find it fails. Double checked this on 2020 M1 and Ubuntu VM Instance (20.04) machines. Running circom v2.0.4, snarkjs@0.4.16, node v16.15.0.

<img width="1440" alt="Screen Shot 2022-05-11 at 12 57 35 AM" src="https://user-images.githubusercontent.com/70081547/167772220-cec450a0-3cd3-4c6b-8938-1078daa8b827.png">

**Comment by TalDerei** [comment]
> There might be an issue with circom@2.0.4 [iden3/snarkjs#145](https://github.com/iden3/snarkjs/issues/145)

I think you might be on to something. I woke up this morning, and the repo randomly started working on my M1 again, but is failing on Linux distros. Interesting ~

**Comment by remi-gai** [comment]
Same issue. Changing snarkjs version to "^0.4.26" fixed it.

**Comment by sragss** [comment]
Should be resolved.
